video_settings:
  frame_difference_threshold: 0.02
  part_frame_hold_seconds: 0.5
  persistence_groups:
    - ["FEMALE_BREAST_EXPOSED", "FEMALE_BREAST_COVERED"]

censor_settings:
  enabled_parts:
    - "FEMALE_BREAST_EXPOSED"
    - "FEMALE_BREAST_COVERED"
    - "BUTTOCKS_EXPOSED"
    - "BUTTOCKS_COVERED"
    - "ANUS_EXPOSED"
    - "ANUS_COVERED"
    - "FEMALE_GENITALIA_EXPOSED"
    - "FEMALE_GENITALIA_COVERED"
    - "MALE_GENITALIA_EXPOSED"

  merge_settings:
    merge_groups:
      - ["FEMALE_BREAST_EXPOSED", "FEMALE_BREAST_COVERED"]
      - ["FEMALE_GENITALIA_EXPOSED", "FEMALE_GENITALIA_COVERED"]
      - ["ANUS_EXPOSED", "ANUS_COVERED"]

  default_part_settings:
    censors:
      [
        {
          "effect": "CentricChromaticAberration",
          parameters: { "offset": 2, "blur": 5 },
        },
        { "effect": "Pixelate", parameters: { "factor": 10 } },
      ]
    mask: "Ellipse"
    margin: 0.2

  FEMALE_GENITALIA_EXPOSED:
    state: "protected"
    margin: -0.25
    mask: RoundedBox
    censors:
      - effect: DevText
        parameters: { "font_percent": 0.8, "font": "comic" }
      - effect: "Outline"
        parameters:
          thickness: 6
          softness: 2
          colour: PINK
      - effect: "Overlay"
        parameters:
          colour: "WHITE"

  ANUS_EXPOSED:
    state: "revealed"
    mask: Ellipse
    censors:
      - effect: "Outline"
        parameters:
          thickness: 6
          softness: 2
          colour: PINK

  ANUS_COVERED:
    state: "revealed"
    mask: Ellipse
    censors:
      - effect: "Outline"
        parameters:
          thickness: 6
          softness: 2
          colour: PINK
