video_settings:
  frame_difference_threshold: 0.02
  part_frame_hold_seconds: 0.75
  persistence_groups:
    - ["FEMALE_BREAST_EXPOSED", "FEMALE_BREAST_COVERED"]
    - ["BUTTOCKS_COVERED", "BUTTOCKS_EXPOSED"]

censor_settings:
  enabled_parts:
    - "FEMALE_BREAST_EXPOSED"
    - "FEMALE_BREAST_COVERED"
    - "BUTTOCKS_EXPOSED"
    - "BUTTOCKS_COVERED"
    - "ANUS_EXPOSED"
    - "ANUS_COVERED"
    - "FEMALE_GENITALIA_EXPOSED"
    - "FEMALE_GENITALIA_COVERED"

  merge_settings:
    merge_groups:
      - ["FEMALE_BREAST_EXPOSED", "FEMALE_BREAST_COVERED"]

  default_part_settings:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "BLACK" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]
    mask: "Ellipse"

  BUTTOCKS_EXPOSED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "WHITE" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]
  BUTTOCKS_COVERED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "GREY" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]

  FEMALE_BREAST_EXPOSED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "YELLOW" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]
  FEMALE_BREAST_COVERED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "ORANGE" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]

  FEMALE_GENITALIA_EXPOSED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "BLUE" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]
  FEMALE_GENITALIA_COVERED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "PURPLE" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]

  ANUS_EXPOSED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "PINK" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]
  ANUS_COVERED:
    censors:
      [
        { "effect": "Outline", parameters: { "colour": "RED" } },
        { "effect": "Pixelate", parameters: { "factor": 15 } },
      ]
